apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: lr9qh-2o4-nodejs
  janus-idp.io/tekton: lr9qh-2o4-nodejs
  backstage.io/kubernetes-id: lr9qh-2o4-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: lr9qh-2o4-nodejs
resources:
- deployment.yaml
- route.yaml
- service.yaml
